modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Ketheroth/AgriGUI/issues"
[[mods]]
modId="agrigui"
version="1.16.5-0.2.0"
displayName="AgriGUI"
updateJSONURL="https://ketheroth.com/mods/agrigui.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/agrigui"
logoFile="logo.png"
credits="The AgriCraft Team"
authors="Ketheroth"
description='''
Add GUI to the agricultural journal.
'''
itemIcon="agricraft:agri_journal"
[[dependencies.agrigui]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.agrigui]]
    modId="agricraft"
    mandatory=true
    versionRange="[1.16.5-3.0.6,)"
    ordering="AFTER"
    side="BOTH"
